--Write a pl/sql procedure to get the count of instructors in the given department
SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE TABLE DEPT(ID NUMBER,NAME VARCHAR2(20),DEP VARCHAR2(30));
INSERT INTO DEPT VALUES(1,'RAHUL','COMPUTER');
INSERT INTO DEPT VALUES(2,'ROHITH','MATHS');
INSERT INTO DEPT VALUES(3,'NIKHITHA','COMPUTER');
INSERT INTO DEPT VALUES(4,'RENIYA','MATHS');
COMMIT;
CREATE OR REPLACE PROCEDURE D(DNAME VARCHAR2,T OUT NUMBER) IS 
BEGIN
SELECT COUNT(*) INTO T FROM DEPT WHERE DEP=DNAME;
END;
/
DECLARE
DNAME VARCHAR2(30):='COMPUTER';
TOTAL NUMBER;
BEGIN
D(DNAME,TOTAL);
DBMS_OUTPUT.PUT_LINE('COUNT:'||TOTAL);
END;
/
