SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE TABLE SAILOR(SID NUMBER,NAME VARCHAR2(20),RATE NUMBER);
INSERT INTO SAILOR VALUES(1,'AMAL',4),(2,'KAMAL',5),(3,'VIMAL',6),(4,'MALU',9);
DECLARE
CURSOR sailor_sc IS SELECT SID,NAME,RATE FROM SAILOR;
V_SID SAILOR.SID % TYPE;
V_NAME SAILOR.NAME%TYPE;
V_RATE SAILOR.RATE % TYPE;

BEGIN

OPEN sailor_sc;

LOOP
FETCH sailor_sc INTO V_SID,V_NAME,V_RATE;
EXIT WHEN sailor_sc % NOTFOUND;
DBMS_OUTPUT.PUT_LINE('STD : '||V_SID||' NAME : '||V_NAME||' RATING : '||V_RATE);
END LOOP;
CLOSE sailor_sc;
END;
/

