--Write a pl/sql function that computes and returns the maximum of two values.
SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE FUNCTION M(N1 IN NUMBER,N2 IN NUMBER) 
RETURN NUMBER IS 
BEGIN
IF N1>N2 THEN 
RETURN N1;
ELSE 
RETURN N2;
END IF; 
END M;
/
DECLARE 
N1 NUMBER:=10;
N2 NUMBER:=30;
TEMP NUMBER;
BEGIN
TEMP:=M(N1,N2);
DBMS_OUTPUT.PUT_LINE('THE GREATES NUMBER IS '||TEMP);
END;
/