SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE OR REPLACE FUNCTION prime(n IN NUMBER)
RETURN VARCHAR2 IS 
i NUMBER;
BEGIN
FOR i IN 2 ..n-1 LOOP
IF MOD(n,i)=0  THEN 
RETURN 'NOT_PRIME';
END IF;
END LOOP;
RETURN 'PRIME';
END prime;
/

DECLARE
n NUMBER:=7;
r VARCHAR2(20);
BEGIN
r := prime(n);
DBMS_OUTPUT.PUT_LINE('THE GIVEN NUMBER IS:'||r);
END;
/
