--Write a pl/sql procedure to find the sum of two numbers
SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE OR REPLACE PROCEDURE S(N1 IN NUMBER,N2 IN NUMBER,RESULT OUT NUMBER)
IS 
BEGIN
RESULT:=N1+N2;
END S;
/
DECLARE 
N1 NUMBER:=30;
N2 NUMBER:=40;
TOTAL NUMBER;
BEGIN
S(N1, N2, TOTAL); 
DBMS_OUTPUT.PUT_LINE('SUM OF TWO:'||TOTAL);
END;
/