--Write a pl/sql procedure to insert the roll no. and name of a student into the
--STUDENT table
SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE TABLE STD(ROLL NUMBER,NAME VARCHAR2(30));
CREATE OR REPLACE PROCEDURE INS(A IN NUMBER,B IN VARCHAR2) IS 
BEGIN
INSERT INTO STD (ROLL,NAME) VALUES(A,B);
DBMS_OUTPUT.PUT_LINE('INSERTED');
END INS;
/
DECLARE
A NUMBER:=101;
B VARCHAR2(30):='RAHUL';
BEGIN
INS(A,B);
END;
/