--Write a pl/sql function to print Weekday in letters.
SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE OR REPLACE FUNCTION WE(N IN NUMBER)
RETURN VARCHAR2 IS 
NAME VARCHAR2(30);
BEGIN
CASE N 
WHEN 1 THEN 
NAME:='SUNDAY';
WHEN 2 THEN 
NAME:='MONDAY';
WHEN 3 THEN 
NAME:='TUESDAY';
WHEN 4 THEN 
NAME:='WEDNESDAY';
WHEN 5 THEN 
NAME:='THURSDAY';
WHEN 6 THEN 
NAME:='FRIDAY';
WHEN 7 THEN 
NAME:='SATURDAY';
ELSE 
NAME:='INVALID DAY!';
END CASE;
RETURN NAME;
END WE;
/
DECLARE
N NUMBER:=3;
RESULT VARCHAR2(30);
BEGIN
RESULT:=WE(N);
DBMS_OUTPUT.PUT_LINE('THE GIVEN DAY IS:'||RESULT);
END;
/
